### PR TITLE
ADD

### PR DESCRIPTION
**Pull request by lestercoyoyjr**
A way to make downloaded videos be stored in a default Downloads folder.

### CODE REVIEW

**Comment by EcomGraduates** [comment]
thanks for the contribution! @lestercoyoyjr

**Comment by Lucilandiolemos** [comment]
Could you check the error that is happening between loom-dl.js and node module cjs js?

**Comment by Lucilandiolemos** [comment]
erro: node:internal/modules/cjs/loader:1205 throw err; ^

 Error: Cannot find module 'C:\Users\Lu\loom-dl.js' at Module._resolveFilename (node:internal/modules/cjs/loader:1202:15) at Module._load (node:internal/modules/cjs/loader:1027:27) at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:187:14) at node:internal/main/run_main_module:28:49 { code: 'MODULE_NOT_FOUND', requireStack:

**Comment by Lucilandiolemos** [comment]
Could you help me with this mistake? two weeks ago it was working normally. Now it's giving this error. I've tried every method available on the internet to fix this error and it doesn't work!

**Comment by EcomGraduates** [comment]
Will look into this and push an update. Can you provide how you’re using
it? In a project or via the cli?

**Comment by Lucilandiolemos** [comment]
node internal modules cjs loader 1205

**Comment by Lucilandiolemos** [comment]
Sem título

Loom Download is extracted in files and programs, just like node.js

**Comment by Lucilandiolemos** [comment]
I'm using it via cli

**Comment by lestercoyoyjr** [comment]
hey @Lucilandiolemos seems there's an error in your npm version, cause it's not installed or it was not installed correctly. In the image, when you use `npm -v` throws an error showing the version is not installed when it should:

image


The command should throw something like this:

image

I just tested and it works correctly:

image

image

Can you install/uninstall npm again and check the packages are correctly installed.? [IMPORTANT] : Remember to download npm packages after you cloned the repository in the folder location of repository as the instructions indicate. Best!

**Comment by Lucilandiolemos** [comment]
Friend, I spent 5 hours straight trying to solve this error and I couldn't. I did everything you told me to do and nothing worked. QUIT! But thank you for your attention and congratulations on your Loom Download project, as it was very good while it was running here.

**Comment by Lucilandiolemos** [comment]
I searched a lot on the internet about it, I did all the guidelines I could find and nothing. I don't know why the node.js suddenly stopped working

**Comment by EcomGraduates** [comment]
> I searched a lot on the internet about it, I did all the guidelines I could find and nothing. I don't know why the node.js suddenly stopped working

you could try and uninstall node all together and reinstall. That's surprising I've never seen node react this way. Maybe you ran some sort of tool that could have potentially corrupted your node installation

**Comment by Lucilandiolemos** [comment]
I've done this several times today. I uninstalled it and installed it again. But, the same error always occurs.

**Comment by Lucilandiolemos** [comment]
If you could do a remote access on my machine, maybe you could! However, I have tested all the methods available on the internet and nothing has fixed the error.

**Comment by aik099** [comment]
@Lucilandiolemos , 

1. after uninstalling the NodeJS have the `node -v` and `npm -v` command both return an error, that no such apps exist?
2. are you using the official NodeJS download page: https://nodejs.org/en/download ?
3. have you tried installing the NodeJS 20.12.2 version (LTS), which is more stable?
4. have you installed dependencies using the `npm install` command and were there any errors?

Based on the screenshots you've provided I was able to understand this:

1. you're having an error similar to this:
```
AuthorizationManager check failed.
At line:1 char:1
+ C:\scriptpath\scriptname.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```
2. you're using MS Windows
3. you're using PowerShell
5. the URL in the error leads to the https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.4 page

It appears, that PowerShell considers the current NodeJS installation as an insecure download and blocks the "npm" from running. Due to that reason the "npm" can't work or install needed dependencies.

Possible solutions:

1. use "cmd" instead of the PowerShell (won't check anything security-related, that causes the error now)
2. or:
   1. properly uninstall NodeJS using the official uninstaller
   2. properly install NodeJS using the official installer
   3. unblock the problematic files using https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/unblock-file?view=powershell-7.4 article (or better yet unblock downloaded NodeJS installation file before using it)
   4. install dependencies using the `npm install` command

**Comment by Lucilandiolemos** [comment]
I've already tried the part about releasing Power Shell policies, but I'll try again one last time, following the steps you suggest.

**Comment by Lucilandiolemos** [comment]
Your environment has been set up for using Node.js 20.12.2 (x64) and npm.

C:\Users\Lu>node -v
v20.12.2

C:\Users\Lu>npm -v
10.5.0

C:\Users\Lu>npm list
C:\Users\Lu
`-- (empty)


C:\Users\Lu>node loom-dl.js --url 
node:internal/modules/cjs/loader:1146
  throw err;
  ^

Error: Cannot find module 'C:\Users\Lu\loom-dl.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.12.2

C:\Users\Lu>node 'loom-dl.js' --url 
node:internal/modules/cjs/loader:1146
  throw err;
  ^

Error: Cannot find module 'C:\Users\Lu\'loom-dl.js''
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.12.2

C:\Users\Lu>node loom-dl --url 
node:internal/modules/cjs/loader:1146
  throw err;
  ^

Error: Cannot find module 'C:\Users\Lu\loom-dl'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.12.2

C:\Users\Lu>npm install
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\Lu\package.json
npm ERR! errno -4058
npm ERR! enoent Could not read package.json: Error: ENOENT: no such file or directory, open 'C:\Users\Lu\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in: C:\Users\Lu\AppData\Local\npm-cache\_logs\2024-05-01T23_02_02_387Z-debug-0.log

C:\Users\Lu>npm start
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\Lu\package.json
npm ERR! errno -4058
npm ERR! enoent Could not read package.json: Error: ENOENT: no such file or directory, open 'C:\Users\Lu\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in: C:\Users\Lu\AppData\Local\npm-cache\_logs\2024-05-01T23_02_46_529Z-debug-0.log

C:\Users\Lu>

**Comment by aik099** [comment]
@Lucilandiolemos ,

Based on the output you've provided we're moving in the correct direction.

Please execute `npm install` and `node 'loom-dl.js' --url ...` (replace `...` with needed URL) the commands in a folder, where you cloned this repo (where `loom-dl.js` and `package.json` file exist).

**Comment by Lucilandiolemos** [comment]
image

**Comment by Lucilandiolemos** [comment]
image

**Comment by Lucilandiolemos** [comment]
image

**Comment by Lucilandiolemos** [comment]
image

**Comment by Lucilandiolemos** [comment]
image

**Comment by Lucilandiolemos** [comment]
image


I downloaded the node.js from the official link youê guided me, where it already comes with the NPM

**Comment by Lucilandiolemos** [comment]
image


First mistake!

**Comment by aik099** [comment]
Based on your screenshots you've done something wrong:

The README says, that:

1. you need to clone this repo somewhere (not even near NodeJS installation folder or `node_modules` folder)
2. in that cloned folder you need to run `npm install`
3. in that cloned folder you need to execute the `node loom-dl.js ...` commands

According to the above screenshots you seem to have `loom-dl.js` somehow installed in the global node_modules folder, which isn't right.

Please follow the installation instructions.

**Comment by Lucilandiolemos** [comment]
image


Run the commands inside the directory: C:\Program Files\nodejs\node_modules


new erro

**Comment by Lucilandiolemos** [comment]
image

**Comment by Lucilandiolemos** [comment]
Thank you very much friend. It took me a while to understand his initial instructions, because of the translation into my language. However, I have now been able to understand its final guidelines and also download the necessary pakages.

**Comment by aik099** [comment]
Thank God! We've made it.

**Comment by Lucilandiolemos** [comment]
Yes, we did it!🙏

**Pull request merged**
